# Generated by Django 4.2 on 2024-11-14 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_profile_user'),
    ]

    operations = [
        # This migration was incorrectly trying to rename a non-existent field
        # The User model already has 'phone' field from the initial migration
        # No operations needed
    ]

