# Generated by Django 4.2 on 2024-11-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_rename_phone_number_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
