# Generated by Django 4.2 on 2025-02-15 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_user_apple_id_user_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apple_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
    ]
