# Generated by Django 4.2 on 2024-12-04 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_whishlist_review_productfaq_notification_coupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whishlist',
            new_name='Wishlist',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='shipping_amount',
            new_name='shipping_ammount',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='shipping_amount',
            new_name='shipping_ammount',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='shipping_amount',
            new_name='shipping_ammount',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
