# Generated by Django 4.2 on 2024-12-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_coupon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorderitem',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Cart Order Item'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={},
        ),
    ]
