# Generated by Django 4.2 on 2024-12-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cartorderitem_options_alter_coupon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Coupons'},
        ),
    ]
