# Generated by Django 4.2 on 2024-12-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_coupon_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_more', models.CharField(default='View All', max_length=10)),
                ('currency_sign', models.CharField(default='$', max_length=10)),
                ('currency_abbreviation', models.CharField(default='USD', max_length=10)),
                ('service_fee_percentage', models.IntegerField(default=5, help_text='NOTE: Numbers added here are in percentage (%)ve.g 4%')),
                ('service_fee_flat_rate', models.DecimalField(decimal_places=2, default=0.7, help_text='NOTE: Add the amount you want to charge as service fee e.g $2.30', max_digits=12)),
                ('service_fee_charge_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat_rate', 'Flat Rate')], default='percentage', max_length=30)),
                ('enforce_2fa', models.BooleanField(default=True)),
                ('activate_affiliate_system', models.BooleanField(default=True)),
                ('send_email_notifications', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
