# Generated by Django 4.2 on 2024-12-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_configsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigSettings',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='stripe_sesion_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
