# Generated by Django 4.2 on 2025-01-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_notification_user_alter_notification_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.FileField(blank=True, default='color.jpg', null=True, upload_to='colors'),
        ),
    ]
