# Generated by Django 4.2 on 2025-01-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_timer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
