# Generated by Django 4.2 on 2025-01-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_homepagecarousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageCarousel',
        ),
    ]
