# Generated by Django 4.2 on 2025-01-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcarousel',
            name='type',
            field=models.CharField(choices=[('default', 'Default'), ('most_viewed', 'Most Viewed')], default='default', max_length=20),
        ),
        migrations.CreateModel(
            name='MostViewedCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='most_viewed_carousels', to='store.product')),
            ],
        ),
    ]
