# Generated by Django 4.2 on 2025-01-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_productcarousel_type_mostviewedcarousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcarousel',
            name='type',
        ),
        migrations.DeleteModel(
            name='MostViewedCarousel',
        ),
    ]
