# Generated by Django 4.2 on 2025-01-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_productcarousel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_oferta_do_dia',
            field=models.BooleanField(default=False),
        ),
    ]
