# Generated by Django 4.2 on 2025-01-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_is_oferta_do_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_oferta_do_dia',
        ),
    ]
