# Generated by Django 4.2 on 2025-01-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_product_is_oferta_do_dia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCarousel',
            new_name='OffersCarousel',
        ),
    ]
