# Generated by Django 4.2 on 2025-01-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_rename_productcarousel_offerscarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_cart_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
