# Generated by Django 4.2 on 2025-02-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_gallery_color_alter_gallery_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('cart_id', 'product', 'color', 'size')},
        ),
    ]
