# Generated by Django 4.2 on 2025-04-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_cart_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='mobile',
            new_name='phone',
        ),
    ]
