# Generated by Django 4.2 on 2025-07-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_carouselautomationproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselAutomationProxy',
        ),
    ]
