# Generated by Django 4.2 on 2025-07-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_delete_carouselautomationproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostViewedCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mais Vendidos', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_update', models.BooleanField(default=True, help_text='Automatically update with most viewed products')),
                ('max_products', models.PositiveIntegerField(default=10, help_text='Maximum number of products to display')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='most_viewed_carousels', to='store.product')),
            ],
            options={
                'verbose_name': 'Most Viewed Carousel',
                'verbose_name_plural': 'Most Viewed Carousels',
            },
        ),
    ]
