# Generated by Django 4.2 on 2025-07-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_mostviewedcarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_most_viewed',
            field=models.BooleanField(default=True, help_text='Show this product in the Most Viewed carousel'),
        ),
    ]

