# Generated by Django 4.2 on 2025-08-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_product_show_in_most_viewed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MostViewedCarousel',
        ),
    ]
